name: build-release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag Name
        # trim prefix from ref to get tag name
        run: echo "TAG_NAME=${GITHUB_REF#'refs/tags/'}" >> $GITHUB_ENV
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Version-stamp Header file
        env:
          RELEASE_URL: ${{ steps.get_release.outputs.html_url }}
        run: |
          echo "// Unmoving $TAG_NAME downloaded from Github at $RELEASE_URL" > header_stub.hpp
          cat header_stub.hpp unmoving/include/unmoving/PSXFixed.hpp > PSXFixed.hpp
      - name: Upload Header file
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./PSXFixed.hpp
          asset_name: PSXFixed.hpp
          asset_content_type: text/plain
      - name: Format Docs Version Name
        # trim patch version off version number as minor version specifies ABI changes
        run: echo "DOCS_VERSION=${TAG_NAME%.*}" >> $GITHUB_ENV
      - name: Build Doxygen Docs
        uses: mattnotmitt/doxygen-action@v1.3.3
      - name: Set up latest docs auto-linking
        # make docs folder, move docs there, call script to generate HTML redirect in index
        run: |
          mkdir docs
          cp -R html docs/$DOCS_VERSION
          ./generate_index $DOCS_VERSION
      - name: Deploy Docs to github-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs
          clean: false
